import { ProjectScenario } from './scenarios';

export function generateSKiDL(scenario: ProjectScenario): string {
  let skidl = `from skidl import *\n\n# Schematic generated by VibePCB for ${scenario.title}\n\n`;

  // Create component instances
  skidl += `# Component Definitions\n`;
  scenario.components.forEach(comp => {
    skidl += `${comp.id.toLowerCase()} = Part('${comp.footprint.split(':')[0]}', '${comp.name}', value='${comp.value}', footprint='${comp.footprint}')\n`;
  });

  skidl += `\n# Net Connections\n`;
  scenario.nets.forEach(net => {
    const connStr = net.connections
      .map(c => `${c.componentId.toLowerCase()}['${c.pinNum}']`)
      .join(' & ');
    skidl += `Net('${net.name}') += ${connStr}\n`;
  });

  skidl += `\nERC()\ngenerate_netlist()\n`;
  return skidl;
}

export function generateBOM(scenario: ProjectScenario): string {
  let csv = `Designator,Comment,Footprint,Quantity,LCSC Part Number,Manufacturer\n`;
  scenario.components.forEach(comp => {
    let lcsc = 'N/A';
    let manufacturer = 'Generic';
    if (comp.id === 'U1' && scenario.id === 'esp32-sensor') {
      lcsc = 'C2913148';
      manufacturer = 'Espressif Systems';
    } else if (comp.id === 'U2' && scenario.id === 'esp32-sensor') {
      lcsc = 'C347228';
      manufacturer = 'Diodes Incorporated';
    } else if (comp.id === 'U3' && scenario.id === 'esp32-sensor') {
      lcsc = 'C92379';
      manufacturer = 'Sensirion';
    } else if (comp.id === 'J1') {
      lcsc = 'C319343';
      manufacturer = 'HRO';
    } else if (comp.id === 'D1' || comp.id === 'D2') {
      lcsc = 'C11223';
      manufacturer = 'Everlight';
    } else if (comp.id === 'U1' && scenario.id === 'lipo-charger') {
      lcsc = 'C15938';
      manufacturer = 'Nanomicro';
    } else if (comp.id === 'U2' && scenario.id === 'lipo-charger') {
      lcsc = 'C8523';
      manufacturer = 'Fortune Semi';
    }
    csv += `"${comp.id}","${comp.value}","${comp.footprint}",1,"${lcsc}","${manufacturer}"\n`;
  });
  return csv;
}

export function generateKiCadSch(scenario: ProjectScenario): string {
  return `(kicad_sch (version 20211123) (generator vibe_pcb)
  (uuid ${Math.random().toString(36).substring(2, 10)})
  (paper "A4")
  (title_block
    (title "${scenario.title}")
    (company "VibePCB AI")
    (comment 1 "Generated via natural language vibe coding")
  )
  ${scenario.components.map((comp, idx) => `
  (symbol (lib_id "${comp.footprint}") (at ${comp.x} ${comp.y} 0)
    (in_bom yes) (on_board yes)
    (uuid ${comp.id}-${idx})
    (property "Reference" "${comp.id}" (at ${comp.x} ${comp.y - 10} 0))
    (property "Value" "${comp.value}" (at ${comp.x} ${comp.y + 10} 0))
  )`).join('')}
)`;
}

export function generateKiCadPCB(scenario: ProjectScenario): string {
  return `(kicad_pcb (version 20211014) (generator vibe_pcb)
  (general
    (thickness 1.6)
  )
  (paper "A4")
  (setup
    (grid 1.27)
    (grid_origin 0 0)
  )
  (net_classes
    (net_class Default "Default class"
      (clearance 0.2)
      (trace_width 0.25)
      (via_dia 0.8)
      (via_drill 0.4)
    )
  )
  (gr_rect (start 0 0) (end ${scenario.boardWidth} ${scenario.boardHeight}) (layer "Edge.Cuts") (width 0.15))
  ${scenario.pcbComponents.map((comp, idx) => `
  (footprint "${comp.footprint}" (layer "F.Cu") (at ${comp.x} ${comp.y} ${comp.rotation})
    (uuid ${comp.id}-${idx})
    (property "Reference" "${comp.id}" (at 0 -3 0))
    (property "Value" "${comp.value}" (at 0 3 0))
  )`).join('')}
)`;
}
